[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "db-dtypes"
version = "1.7.0"
description = "Pandas Data Types for SQL systems (BigQuery, Spanner)"
keywords = [ "sql", "pandas",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14", "Operating System :: OS Independent", "Topic :: Database :: Front-Ends",]
requires-python = ">=3.10"
dependencies = [ "numpy >= 1.24.0, <= 2.2.6 ; python_version == '3.10'", "numpy >= 1.24.0 ; python_version != '3.10'", "packaging >= 24.2.0", "pandas >= 1.5.3, < 4.0.0", "pyarrow >= 13.0.0",]

[[project.authors]]
name = "The db-dtypes Authors"
email = "googleapis-packages@google.com"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/googleapis/google-cloud-python/tree/main/packages/db-dtypes"

[project.optional-dependencies]
testing = [ "pytest",]

[tool.setuptools]
packages = [ "db_dtypes",]
platforms = [ "Posix",]
include-package-data = false
