[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "sagemaker-mlflow"
version = "0.4.0"
description = "AWS Plugin for MLflow with SageMaker"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Natural Language :: English", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12",]
requires-python = ">= 3.8"
dependencies = [ "boto3>=1.34", "mlflow-skinny>=2.8",]
[[project.authors]]
name = "Amazon Web Services"

[project.license]
text = "Apache License 2.0"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/aws/sagemaker-mlflow"

[project.optional-dependencies]
full = [ "mlflow>=2.8",]
test = [ "boto3", "coverage>=5.2,<6.2", "mlflow-skinny", "pytest", "pytest-cov", "pytest-rerunfailures", "pytest-timeout", "pytest-xdist", "moto",]
test_prerelease = [ "mlflow", "packaging", "pytest", "moto",]

[tool.setuptools]
include-package-data = false

[project.entry-points."mlflow.tracking_store"]
arn = "sagemaker_mlflow.mlflow_sagemaker_store:MlflowSageMakerStore"

[project.entry-points."mlflow.request_auth_provider"]
arn = "sagemaker_mlflow.auth_provider:AuthProvider"

[project.entry-points."mlflow.request_header_provider"]
arn = "sagemaker_mlflow.mlflow_sagemaker_request_header_provider:MlflowSageMakerRequestHeaderProvider"

[project.entry-points."mlflow.model_registry_store"]
arn = "sagemaker_mlflow.mlflow_sagemaker_registry_store:MlflowSageMakerRegistryStore"

[project.entry-points."mlflow.scorer_store"]
arn = "sagemaker_mlflow.mlflow_sagemaker_scorer_store:MlflowSageMakerScorerStore"

[project.entry-points."mlflow.workspace_provider"]
arn = "sagemaker_mlflow.mlflow_sagemaker_workspace_store:MlflowSageMakerWorkspaceStore"

[project.entry-points."mlflow.artifact_repository"]
s3 = "sagemaker_mlflow.s3_presigned_artifact_repo:S3PresignedArtifactRepository"

[tool.setuptools.packages.find]
namespaces = false

[tool.black]
line-length = 120
