[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "scalar_fastapi"
version = "1.8.2"
description = "This plugin provides an easy way to render a beautiful API reference based on a OpenAPI/Swagger file with FastAPI."
classifiers = [ "License :: OSI Approved :: MIT License",]
dependencies = []

[[project.authors]]
name = "Scalar"
email = "support@scalar.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/scalar/scalar"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
