[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "extract_msg"
version = "0.55.0"
description = "Extracts emails and attachments saved in Microsoft Outlook's .msg files"
requires-python = ">=3.8"
dependencies = [ "olefile==0.47", "tzlocal>=4.2,<6", "compressed-rtf>=1.0.6,<2", "ebcdic>=1.1.1,<2", "beautifulsoup4>=4.11.1,<4.14", "RTFDE>=0.1.1,<0.2", "red-black-tree-mod>=1.20, <=1.23",]

[[project.authors]]
name = "Destiny Peterson & Matthew Walker"
email = "arceusthe@gmail.com"

[[project.authors]]
email = "mattgwwalker@gmail.com"

[project.license]
text = "GPL"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/TeamMsgExtractor/msg-extractor"
Download = "https://github.com/TeamMsgExtractor/msg-extractor/archives/master"

[project.optional-dependencies]
all = [ "extract-msg[mime]", "extract-msg[image]", "extract-msg[encoding]",]
mime = [ "python-magic>=0.4.27,<0.5",]
image = [ "Pillow>=9.5.0,<10",]
encoding = [ "chardet>=3.0.0,<6",]
readthedocs = [ "sphinx-rtd-theme",]

[project.scripts]
extract_msg = "extract_msg.__main__:main"

[tool.setuptools]
py-modules = [ "extract_msg",]
packages = [ "extract_msg",]
include-package-data = true
