[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "dash_html_components"
version = "2.0.0"
description = "Vanilla HTML components for Dash"
dependencies = []

[[project.authors]]
name = "Chris Parmer <chris@plotly.com>"
email = "chris@plotly.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/plotly/dash-html-components"

[tool.setuptools]
packages = [ "dash_html_components",]
include-package-data = true
