[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "alibabacloud_tea_openapi"
version = "0.4.4"
description = "Alibaba Cloud openapi SDK Library for Python"
keywords = [ "alibabacloud", "tea", "openapi",]
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Topic :: Software Development",]
requires-python = ">=3.7"
dependencies = [ "darabonba-core>=1.0.3, <2.0.0", "alibabacloud_credentials>=1.0.2, <2.0.0", "alibabacloud_gateway_spi>=0.0.2, <1.0.0", "cryptography>=3.0.0, <46.0.0; python_version<'3.8'", "cryptography>=3.0.0, <47.0.0; python_version>='3.8'", "alibabacloud_tea_util>=0.3.13, <1.0.0",]

[[project.authors]]
name = "Alibaba Cloud SDK"
email = "sdk-team@alibabacloud.com"

[project.license]
text = "Apache License 2.0"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/aliyun/darabonba-openapi"

[tool.setuptools]
include-package-data = true
platforms = [ "any",]

[tool.setuptools.packages.find]
exclude = [ "tests*",]
namespaces = false
