[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "yamale"
version = "6.1.0"
description = "A schema and validator for YAML."
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Operating System :: OS Independent", "License :: OSI Approved :: MIT License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14",]
requires-python = ">=3.8"
dependencies = [ "pyyaml",]

[[project.authors]]
name = "Bo Lopker"
email = "dev-api@23andme.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/23andMe/Yamale"

[project.optional-dependencies]
ruamel = [ "ruamel.yaml",]

[project.scripts]
yamale = "yamale.command_line:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
