[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "iopath"
version = "0.1.10"
description = "A library for providing I/O abstraction."
requires-python = ">=3.6"
dependencies = [ "tqdm", "typing_extensions", "portalocker", "dataclasses; python_version<'3.7'",]

[[project.authors]]
name = "FAIR"

[project.license]
text = "MIT licensed, as found in the LICENSE file"

[project.urls]
Homepage = "https://github.com/facebookresearch/iopath"

[project.optional-dependencies]
aws = [ "boto3",]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
