[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "wikipedia"
version = "1.4.0"
description = "Wikipedia API for Python"
keywords = [ "python", "wikipedia", "API",]
readme = "README.rst"
classifiers = [ "Development Status :: 4 - Beta", "Topic :: Software Development :: Libraries", "License :: OSI Approved :: MIT License", "Programming Language :: Python", "Programming Language :: Python :: 3",]
dependencies = [ "beautifulsoup4", "requests>=2.0.0,<3.0.0",]

[[project.authors]]
name = "Jonathan Goldsmith"
email = "jhghank@gmail.com"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/goldsmith/Wikipedia"

[tool.setuptools]
packages = [ "wikipedia",]
include-package-data = false
