[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "requests-oauth"
version = "0.4.1"
description = "Hook for adding Open Authentication support to Python-requests HTTP library."
keywords = [ "requests", "python-requests", "OAuth", "open authentication",]
readme = "README.md"
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "Programming Language :: Python", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Topic :: Internet :: WWW/HTTP", "Topic :: Software Development :: Libraries :: Python Modules",]
dependencies = [ "requests>=0.12.1",]

[[project.authors]]
name = "Miguel Araujo"
email = "miguel.araujo.perez@gmail.com"

[project.license]
text = "BSD"

[project.urls]
Homepage = "http://github.com/maraujop/requests-oauth"

[tool.setuptools]
zip-safe = false
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
