[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "torchviz"
version = "0.0.3"
description = "A small package to create visualizations of PyTorch execution graphs"
dependencies = [ "torch", "graphviz",]

[[project.authors]]
name = "Sergey Zagoruyko"
email = "sergey.zagoruyko@enpc.fr"

[project.license]
text = "BSD"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/pytorch/pytorchviz"

[tool.setuptools]
zip-safe = true
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "test",]
namespaces = false
