[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "pyxlsb"
version = "1.0.10"
description = "Excel 2007-2010 Binary Workbook (xlsb) parser"
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9",]

[[project.authors]]
name = "William Turner"
email = "willtur.will@gmail.com"

[project.license]
text = "LGPLv3+"

[project.urls]
Homepage = "https://github.com/willtrnr/pyxlsb"

[tool.setuptools]
packages = [ "pyxlsb",]
include-package-data = false
