[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "setuptools_download"
version = "1.1.0"
description = "setuptools plugin to download external files"
classifiers = [ "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy",]
requires-python = ">=3.8"
dependencies = [ "setuptools>=46.1.0",]

[[project.authors]]
name = "Anthony Sottile"
email = "asottile@umich.edu"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/asottile/setuptools-download"

[tool.setuptools]
py-modules = [ "setuptools_download",]
license-files = [ "LICENSE",]
include-package-data = false

[project.entry-points."distutils.commands"]
setuptools_download = "setuptools_download:setuptools_download"
install_setuptools_download = "setuptools_download:install_setuptools_download"

[project.entry-points."setuptools.finalize_distribution_options"]
setuptools_download = "setuptools_download:finalize_distribution"
