[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "xlsxwriter"
version = "3.2.9"
description = "A Python module for creating Excel XLSX files."
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "License :: OSI Approved :: BSD License", "Programming Language :: Python", "Programming Language :: Python :: 3 :: Only", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13",]
requires-python = ">=3.8"

[[project.authors]]
name = "John McNamara"
email = "jmcnamara@cpan.org"

[project.license]
text = "BSD-2-Clause"

[project.urls]
Homepage = "https://github.com/jmcnamara/XlsxWriter"

[tool.setuptools]
packages = [ "xlsxwriter",]
script-files = [ "examples/vba_extract.py",]
include-package-data = false
