[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "requests-sigv4"
version = "0.1.6"
description = "Library for making sigv4 requests to AWS API endpoints"
keywords = [ "aws", "requests", "sign", "sigv4",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Natural Language :: English", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8",]
dependencies = [ "requests", "requests-aws-sign", "boto3",]
[[project.authors]]
name = "ClearDATA Engineering"
email = "support@cleardata.com"

[project.license]
text = "Apache License 2.0"

[project.readme]
text = "Library for making sigv4 requests to AWS API endpoints"
content-type = "text/plain"

[project.urls]
Homepage = "https://github.com/cleardataeng/requests-sigv4"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests*",]
namespaces = false
