[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "snapshot-restore-py"
version = "1.0.0"
description = "Runtime Hooks for AWS Lambda SnapStart - Python"
keywords = [ "serverless", "aws", "lambda", "python", "snapstart", "runtime", "hooks",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Natural Language :: English", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent",]
requires-python = ">=3.9"
dependencies = []
[[project.authors]]
name = "Amazon Web Services"

[project.license]
text = "Apache License 2.0"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/aws/snapshot-restore-py"

[tool.setuptools]
py-modules = [ "snapshot_restore_py",]
include-package-data = false
