[build-system]
requires = [ "setuptools>=61.2", "pbr>=1.8",]
build-backend = "setuptools.build_meta"

[project]
name = "lockfile"
description = "Platform-independent file locking module"
classifiers = [ "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Operating System :: POSIX :: Linux", "Operating System :: MacOS", "Operating System :: Microsoft :: Windows :: Windows NT/2000", "Operating System :: POSIX", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Topic :: Software Development :: Libraries :: Python Modules",]
readme = "README.rst"
dynamic = [ "version",]
[[project.authors]]
name = "OpenStack"
email = "openstack-dev@lists.openstack.org"

[project.urls]
Homepage = "http://launchpad.net/pylockfile"

[tool.setuptools]
include-package-data = false
