[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "cfn_flip"
version = "1.3.0"
description = "Convert AWS CloudFormation templates between JSON and YAML formats"
dependencies = [ "Click", "PyYAML>=4.1", "six",]

[[project.authors]]
name = "Steve Engledow"
email = "sengledo@amazon.co.uk"

[project.license]
text = "Apache2"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/awslabs/aws-cfn-template-flip"

[project.scripts]
cfn-flip = "cfn_flip.main:main"

[project.optional-dependencies]
testing = [ "pytest>=4.3.0", "pytest-cov", "pytest-runner",]

[tool.setuptools]
zip-safe = false
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
