[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "findspark"
version = "2.0.1"
description = "Find pyspark to make it importable."
readme = {text = "\n        Provides findspark.init() to make pyspark importable as a regular library.\n    ", content-type = "text/plain"}
license = {text = "BSD (3-clause)"}
authors = [
    {name = "Min RK"},
    {email = "benjaminrk@gmail.com"},
]

[project.urls]
Homepage = "https://github.com/minrk/findspark"

[tool.setuptools]
py-modules = ["findspark"]
include-package-data = false

[tool.distutils.bdist_wheel]
universal = true
