[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "Inflector"
version = "3.1.1"
description = "Inflector for Python"
keywords = [ "inflector", "text", "language", "english",]
readme = "README.md"
classifiers = [ "Intended Audience :: Developers", "License :: OSI Approved :: Python Software Foundation License", "Programming Language :: Python", "Topic :: Software Development :: Libraries :: Python Modules",]
[[project.authors]]
name = "Parnell Springmeyer"
email = "parnell@digitalmentat.com"

[project.urls]
Homepage = "https://github.com/ixmatus/inflector"

[tool.setuptools]
packages = [ "inflector",]
zip-safe = false
include-package-data = true

[tool.setuptools.package-dir]
inflector = "inflector"
