[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "json-rpc"
version = "1.15.0"
description = "JSON-RPC transport implementation"
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Operating System :: OS Independent", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Software Development :: Libraries :: Python Modules",]

[[project.authors]]
name = "Kirill Pavlov"
email = "k@p99.io"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/pavlov99/json-rpc"

[project.optional-dependencies]
testing = [ "pytest",]

[tool.setuptools]
license-files = [ "LICENSE.txt",]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
