[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "circuitbreaker"
version = "2.1.3"
description = "Python Circuit Breaker pattern implementation"
readme = "README.rst"
classifiers = [ "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: POSIX", "Operating System :: MacOS", "Operating System :: Unix", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10",]

[[project.authors]]
name = "Fabian Fuelling"
email = "pypi@fabfuel.de"

[project.license]
text = "BSD-3-Clause"

[project.urls]
Homepage = "https://github.com/fabfuel/circuitbreaker"
Download = "https://github.com/fabfuel/circuitbreaker/archive/2.1.3.tar.gz"

[tool.setuptools]
py-modules = [ "circuitbreaker",]
zip-safe = false
include-package-data = true
platforms = [ "any",]
