[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "flask-talisman"
version = "1.1.0"
description = "HTTP security headers for Flask."
keywords = [ "flask", "security", "https", "xss",]
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Topic :: Software Development :: Libraries :: Python Modules", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Operating System :: POSIX", "Operating System :: MacOS", "Operating System :: Unix",]
dependencies = []

[[project.authors]]
name = "Alethea Katherine Flowers"
email = "me@thea.codes"

[project.license]
text = "Apache Software License"

[project.urls]
Homepage = "https://github.com/wntrblm/flask-talisman"

[tool.setuptools]
packages = [ "flask_talisman",]
include-package-data = false
