[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "drf-spectacular-sidecar"
version = "2026.6.1"
description = "Serve self-contained distribution builds of Swagger UI and Redoc with Django"
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Web Environment", "Framework :: Django", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Natural Language :: English", "Programming Language :: Python :: 3", "Topic :: Internet :: WWW/HTTP", "Topic :: Documentation", "Topic :: Software Development :: Code Generators",]
requires-python = ">=3.6"
dependencies = [ "Django>=2.2",]

[[project.authors]]
name = "T. Franzel"
email = "tfranzel@gmail.com"

[project.license]
text = "BSD"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/tfranzel/drf-spectacular-sidecar"
Source = "https://github.com/tfranzel/drf-spectacular-sidecar"
Documentation = "https://drf-spectacular.readthedocs.io"

[tool.setuptools]
packages = [ "drf_spectacular_sidecar",]
include-package-data = true
