[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "mkdocs-monorepo-plugin"
version = "1.1.2"
description = "Plugin for adding monorepository support in Mkdocs."
keywords = [ "mkdocs", "monorepo",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Intended Audience :: Information Technology", "Programming Language :: Python", "Programming Language :: Python :: 3 :: Only", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12",]
requires-python = ">=3.9"
dependencies = [ "mkdocs>=1.0.4", "python-slugify>=4.0.1",]
[[project.authors]]
name = "Bilawal Hameed"
email = "bil@spotify.com"

[project.license]
text = "Apache-2.0"

[project.readme]
text = "This introduces support for the !include syntax in mkdocs.yml, allowing you to import additional Mkdocs navigation.\nIt enables large or complex repositories to have their own sets of docs/ folders, whilst generating only a single Mkdocs site.\nThis is built and maintained by the Backstage open source team."
content-type = "text/plain"

[project.urls]
Homepage = "https://github.com/backstage/mkdocs-monorepo-plugin"

[tool.setuptools]
include-package-data = false

[project.entry-points."mkdocs.plugins"]
monorepo = "mkdocs_monorepo_plugin.plugin:MonorepoPlugin"

[tool.setuptools.packages.find]
namespaces = false
