[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "httpretty"
version = "1.1.4"
description = "HTTP client mock for Python"
readme = "README.rst"
license = {text = "MIT"}
authors = [
    {name = "Gabriel Falcao"},
    {email = "gabriel@nacaolivre.org"},
]
requires-python = ">=3"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Testing",
]
dependencies = []

[project.urls]
Homepage = "https://httpretty.readthedocs.io/en/latest/"
Documentation = "https://httpretty.readthedocs.io/en/latest/"
"Source Code" = "https://github.com/gabrielfalcao/httpretty"
"Issue Tracker" = "https://github.com/gabrielfalcao/httpretty/issues"
"Continuous Integration" = "https://github.com/gabrielfalcao/HTTPretty/actions/workflows/pyenv.yml?query=branch%3Amaster+event%3Apush"
"Test Coverage" = "https://codecov.io/gh/gabrielfalcao/httpretty"

[tool.setuptools]
include-package-data = false
packages = ["httpretty"]
