[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "MainContentExtractor"
version = "0.0.4"
description = "A library to extract the main content from html. Developed for information on LLM and for feeding data into LangChain and LlamaIndex."
requires-python = ">=3.6"
dependencies = [ "trafilatura>=1.6.2", "html2text>=2020.1.16", "beautifulsoup4>=4.12.2",]

[[project.authors]]
name = "HawkClaws"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/HawkClaws/main_content_extractor"
"Source Code" = "https://github.com/HawkClaws/main_content_extractor"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
