[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "verboselogs"
version = "1.7"
description = "Verbose logging level for Python's logging module"
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Intended Audience :: Information Technology", "Intended Audience :: System Administrators", "License :: OSI Approved :: MIT License", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Software Development", "Topic :: Software Development :: Libraries", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: System", "Topic :: System :: Logging", "Topic :: System :: Systems Administration", "Topic :: Terminals",]

[[project.authors]]
name = "Peter Odding"
email = "peter@peterodding.com"

[project.urls]
Homepage = "https://verboselogs.readthedocs.io"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
