[build-system]
requires = [ "setuptools>=61.2", "setuptools_scm",]
build-backend = "setuptools.build_meta"

[project]
name = "kafka-python-ng"
description = "Pure Python client for Apache Kafka"
keywords = [ "apache kafka", "kafka",]
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Software Development :: Libraries :: Python Modules",]
requires-python = ">=3.8"
dynamic = [ "version",]

[[project.authors]]
name = "Dana Powers"
email = "dana.powers@gmail.com"

[[project.maintainers]]
name = "William Barnhart"
email = "williambbarnhart@gmail.com"

[project.license]
text = "Apache License 2.0"

[project.urls]
Homepage = "https://github.com/wbarnha/kafka-python-ng"

[project.optional-dependencies]
crc32c = [ "crc32c",]
lz4 = [ "lz4",]
snappy = [ "python-snappy",]
zstd = [ "zstandard",]
boto = [ "botocore",]
testing = [ "tox", "mock",]

[tool.setuptools]
license-files = [ "LICENSE",]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "test",]
namespaces = false
