[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "google-cloud-asset"
version = "4.4.0"
description = "Google Cloud Asset API client library"
readme = {file = "README.rst", content-type = "text/x-rst"}
license = {text = "Apache-2.0"}
authors = [
    {name = "Google LLC", email = "googleapis-packages@google.com"},
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Internet",
]
dependencies = [
    "google-api-core[grpc] >= 2.17.1, <3.0.0",
    "google-auth >= 2.14.1, <3.0.0,!=2.24.0,!=2.25.0",
    "google-cloud-org-policy >= 1.11.1, <2.0.0",
    "grpcio >= 1.59.0, < 2.0.0",
    "grpcio >= 1.75.1, < 2.0.0; python_version >= '3.14'",
    "proto-plus >= 1.22.3, <2.0.0",
    "proto-plus >= 1.25.0, <2.0.0; python_version >= '3.13'",
    "protobuf >= 4.25.8, < 8.0.0",
    "google-cloud-access-context-manager >= 0.2.0, <1.0.0",
    "google-cloud-os-config >= 1.13.0, <2.0.0",
    "grpc-google-iam-v1 >= 0.14.0, <1.0.0",
]

[project.urls]
Homepage = "https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-asset"

[tool.setuptools]
include-package-data = true
platforms = ["Posix; MacOS X; Windows"]
packages = [
    "google",
    "google.cloud",
    "google.cloud.asset_v1",
    "google.cloud.asset",
    "google.cloud.asset_v1p5beta1",
    "google.cloud.asset_v1p2beta1",
    "google.cloud.asset_v1p1beta1",
    "google.cloud.asset_v1.services",
    "google.cloud.asset_v1.types",
    "google.cloud.asset_v1.services.asset_service",
    "google.cloud.asset_v1.services.asset_service.transports",
    "google.cloud.asset_v1p5beta1.services",
    "google.cloud.asset_v1p5beta1.types",
    "google.cloud.asset_v1p5beta1.services.asset_service",
    "google.cloud.asset_v1p5beta1.services.asset_service.transports",
    "google.cloud.asset_v1p2beta1.services",
    "google.cloud.asset_v1p2beta1.types",
    "google.cloud.asset_v1p2beta1.services.asset_service",
    "google.cloud.asset_v1p2beta1.services.asset_service.transports",
    "google.cloud.asset_v1p1beta1.services",
    "google.cloud.asset_v1p1beta1.types",
    "google.cloud.asset_v1p1beta1.services.asset_service",
    "google.cloud.asset_v1p1beta1.services.asset_service.transports",
]
