[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "Columnar"
version = "1.4.1"
description = "A tool for printing data in a columnar format."
classifiers = [ "Programming Language :: Python :: 3.7", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
dependencies = [ "toolz", "wcwidth",]

[[project.authors]]
name = "Max Taggart"
email = "max.taggart@gmail.com"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
