[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "jsonpath-rw"
version = "1.4.0"
description = "A robust and significantly extended implementation of JSONPath for Python, with a clear AST for metaprogramming."
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 3.3",]
dependencies = [ "ply", "decorator", "six",]
[[project.authors]]
name = "Kenneth Knowles"
email = "kenn.knowles@gmail.com"

[project.license]
text = "Apache 2.0"

[project.urls]
Homepage = "https://github.com/kennknowles/python-jsonpath-rw"

[project.scripts]
"jsonpath.py" = "jsonpath_rw.bin.jsonpath:entry_point"

[tool.setuptools]
packages = [ "jsonpath_rw", "jsonpath_rw.bin",]
include-package-data = false
