[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "argparse_dataclass"
version = "2.0.0"
description = "Declarative CLIs with argparse and dataclasses"
readme = "README.rst"
classifiers = [ "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11",]
requires-python = ">=3.8"

[[project.authors]]
name = "Michael V. DePalatis"
email = "mike@depalatis.net"

[project.urls]
Homepage = "https://github.com/mivade/argparse_dataclass"

[tool.setuptools]
py-modules = [ "argparse_dataclass",]
include-package-data = true
