[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "expiringdict"
version = "1.2.2"
description = "Dictionary with auto-expiring values for caching purposes"
keywords = []
readme = "README.rst"
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.6", "Topic :: Software Development :: Libraries",]
dependencies = [ "typing;python_version<\"3.5\"",]

[[project.authors]]
name = "Mailgun Technologies Inc."
email = "admin@mailgun.com"

[project.license]
text = "Apache 2"

[project.urls]
Homepage = "https://www.mailgun.com/"

[project.optional-dependencies]
tests = [ "dill", "coverage", "coveralls", "mock", "nose",]
testing = [ "dill", "coverage", "coveralls", "mock", "nose",]

[tool.setuptools]
zip-safe = true
include-package-data = true

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
