[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "google-auth-httplib2"
version = "0.4.0"
description = "Google Authentication Library: httplib2 transport"
keywords = [ "google", "auth", "oauth", "client",]
readme = "README.rst"
classifiers = [ "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14", "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Operating System :: POSIX", "Operating System :: Microsoft :: Windows", "Operating System :: MacOS :: MacOS X", "Operating System :: OS Independent", "Topic :: Internet :: WWW/HTTP",]
requires-python = ">=3.10"
dependencies = [ "google-auth >= 1.32.0,<3.0.0", "httplib2 >= 0.19.0,<1.0.0",]

[[project.authors]]
name = "Google Cloud Platform"
email = "googleapis-packages@google.com"

[project.license]
text = "Apache 2.0"

[project.urls]
Homepage = "https://github.com/googleapis/google-cloud-python/packages/google-auth-httplib2"

[tool.setuptools]
py-modules = [ "google_auth_httplib2",]
include-package-data = false
