[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-dotenv"
version = "0.5.2"
description = "A py.test plugin that parses environment files before running tests"
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8",]
dependencies = [ "pytest>=5.0.0", "python-dotenv>=0.9.1",]
[[project.authors]]
name = "Marcel Radischat"
email = "marcel@quiqua.eu"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/quiqua/pytest-dotenv"
Download = "https://github.com/quiqua/pytest-dotenv/tarball/0.5.2"

[tool.setuptools]
packages = [ "pytest_dotenv",]
include-package-data = false

[project.entry-points.pytest11]
dotenv = "pytest_dotenv.plugin"
