[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "django-loginas"
version = "0.3.14"
description = "An app to add a \"Log in as user\" button in the Django user admin page."
keywords = [ "django",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Web Environment", "Framework :: Django", "Framework :: Django :: 2.2", "Framework :: Django :: 3.2", "Framework :: Django :: 4.0", "Framework :: Django :: 4.1", "Framework :: Django :: 4.2", "Framework :: Django :: 5.0", "Framework :: Django :: 5.1", "Framework :: Django :: 5.2", "Framework :: Django :: 6.0", "Intended Audience :: Developers", "Natural Language :: English", "Operating System :: OS Independent", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11",]

[[project.authors]]
name = "Stochastic Technologies"
email = "info@stochastictechnologies.com"

[project.license]
text = "BSD"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/stochastic-technologies/django-loginas/"

[tool.setuptools]
packages = [ "loginas",]
zip-safe = false
include-package-data = true

[tool.setuptools.package-dir]
loginas = "loginas"
