[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "ibm-cos-sdk-s3transfer"
version = "2.16.2"
description = "IBM S3 Transfer Manager"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "Natural Language :: English", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14",]
requires-python = ">= 3.8"
dependencies = [ "ibm-cos-sdk-core==2.16.2",]
[[project.authors]]
name = "IBM"

[project.license]
text = "Apache License 2.0"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/IBM/ibm-cos-sdk-python-s3transfer"

[project.optional-dependencies]
crt = [ "ibm_botocore[crt]>=1.37.4,<2.0a0",]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [ "tests*",]
namespaces = false
