[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "alibabacloud_endpoint_util"
version = "0.0.4"
description = "The endpoint-util module of alibabaCloud Python SDK."
keywords = [ "alibabacloud", "sdk", "tea",]
readme = "README.md"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Topic :: Software Development",]
dependencies = []

[[project.authors]]
name = "Alibaba Cloud"
email = "alibaba-cloud-sdk-dev-team@list.alibaba-inc.com"

[project.license]
text = "Apache License 2.0"

[project.urls]
Homepage = "https://github.com/aliyun/endpoint-util/tree/master/python"

[tool.setuptools]
platforms = [ "any",]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests*",]
namespaces = false
