[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "json2html"
version = "1.3.0"
description = "JSON to HTML Table Representation"
keywords = [ "json", "HTML", "Table",]
readme = "README.rst"
classifiers = []
dependencies = []
[[project.authors]]
name = "Varun Malhotra"
email = "varun2902@gmail.com"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/softvar/json2html"
Download = "https://github.com/softvar/json2html/tarball/1.3.0"

[tool.setuptools]
packages = [ "json2html",]
include-package-data = false
