[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "sqlalchemy-json"
version = "0.7.0"
description = "JSON type with nested change tracking for SQLAlchemy"
keywords = [ "sqlalchemy", "json", "mutable",]
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Topic :: Database",]
requires-python = ">= 3.6"
dependencies = [ "sqlalchemy>=0.7",]

[[project.authors]]
name = "Elmer de Looff"
email = "elmer.delooff@gmail.com"

[project.license]
text = "BSD"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/edelooff/sqlalchemy-json"

[project.optional-dependencies]
dev = [ "pytest",]

[tool.setuptools]
packages = [ "sqlalchemy_json",]
zip-safe = false
include-package-data = false
