[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "dpath"
version = "2.2.0"
description = "Filesystem-like pathing and searching for dictionaries"
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Console", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Topic :: Software Development :: Libraries :: Python Modules", "Typing :: Typed",]
requires-python = ">=3.7"
dependencies = []

[[project.authors]]
name = "Caleb Case"
email = "calebcase@gmail.com"

[[project.authors]]
name = "Andrew Kesterson"
email = "andrew@aklabs.net"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/dpath-maintainers/dpath-python"

[tool.setuptools]
packages = [ "dpath",]
script-files = []
include-package-data = false

[tool.setuptools.package-data]
dpath = [ "py.typed",]
