[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "aws-requests-auth"
version = "0.4.3"
description = "AWS signature version 4 signing process for the python requests module"
classifiers = [ "License :: OSI Approved :: BSD License", "Programming Language :: Python", "Programming Language :: Python :: 3",]
dependencies = [ "requests>=0.14.0",]
[[project.authors]]
name = "David Muller"
email = "davehmuller@gmail.com"

[project.readme]
text = "See https://github.com/davidmuller/aws-requests-auth for installation and usage instructions."
content-type = "text/plain"

[project.urls]
Homepage = "https://github.com/davidmuller/aws-requests-auth"

[tool.setuptools]
packages = [ "aws_requests_auth",]
include-package-data = false
