[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "alibabacloud-credentials-api"
version = "1.0.0"
description = "Alibaba Cloud Gateway SPI SDK Library for Python"
keywords = [ "alibabacloud", "credentials", "api",]
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Topic :: Software Development",]
requires-python = ">=3.7"
dependencies = []

[[project.authors]]
name = "Alibaba Cloud SDK"
email = "sdk-team@alibabacloud.com"

[project.license]
text = "Apache License 2.0"

[project.urls]
Homepage = "https://github.com/aliyun/alibabacloud-gateway"

[tool.setuptools]
include-package-data = true
platforms = [ "any",]

[tool.setuptools.packages.find]
exclude = [ "tests*",]
namespaces = false
