[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "google-cloud-discoveryengine"
version = "0.20.0"
description = "Google Cloud Discoveryengine API client library"
readme = "README.rst"
license = {text = "Apache-2.0"}
authors = [
    {name = "Google LLC"},
    {email = "googleapis-packages@google.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Internet",
]
requires-python = ">=3.10"
dependencies = [
    "google-api-core[grpc] >= 2.17.1, <3.0.0",
    "google-auth >= 2.14.1, <3.0.0,!=2.24.0,!=2.25.0",
    "grpcio >= 1.59.0, < 2.0.0",
    "grpcio >= 1.75.1, < 2.0.0; python_version >= '3.14'",
    "proto-plus >= 1.22.3, <2.0.0",
    "proto-plus >= 1.25.0, <2.0.0; python_version >= '3.13'",
    "protobuf >= 4.25.8, < 8.0.0",
]

[project.urls]
Homepage = "https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-discoveryengine"

[tool.setuptools]
platforms = ["Posix; MacOS X; Windows"]
packages = [
    "google",
    "google.cloud",
    "google.cloud.discoveryengine_v1alpha",
    "google.cloud.discoveryengine_v1beta",
    "google.cloud.discoveryengine",
    "google.cloud.discoveryengine_v1",
    "google.cloud.discoveryengine_v1alpha.services",
    "google.cloud.discoveryengine_v1alpha.types",
    "google.cloud.discoveryengine_v1alpha.services.site_search_engine_service",
    "google.cloud.discoveryengine_v1alpha.services.session_service",
    "google.cloud.discoveryengine_v1alpha.services.serving_config_service",
    "google.cloud.discoveryengine_v1alpha.services.document_service",
    "google.cloud.discoveryengine_v1alpha.services.user_event_service",
    "google.cloud.discoveryengine_v1alpha.services.project_service",
    "google.cloud.discoveryengine_v1alpha.services.completion_service",
    "google.cloud.discoveryengine_v1alpha.services.data_store_service",
    "google.cloud.discoveryengine_v1alpha.services.grounded_generation_service",
    "google.cloud.discoveryengine_v1alpha.services.estimate_billing_service",
    "google.cloud.discoveryengine_v1alpha.services.search_tuning_service",
    "google.cloud.discoveryengine_v1alpha.services.chunk_service",
    "google.cloud.discoveryengine_v1alpha.services.sample_query_set_service",
    "google.cloud.discoveryengine_v1alpha.services.control_service",
    "google.cloud.discoveryengine_v1alpha.services.recommendation_service",
    "google.cloud.discoveryengine_v1alpha.services.rank_service",
    "google.cloud.discoveryengine_v1alpha.services.engine_service",
    "google.cloud.discoveryengine_v1alpha.services.conversational_search_service",
    "google.cloud.discoveryengine_v1alpha.services.schema_service",
    "google.cloud.discoveryengine_v1alpha.services.evaluation_service",
    "google.cloud.discoveryengine_v1alpha.services.acl_config_service",
    "google.cloud.discoveryengine_v1alpha.services.search_service",
    "google.cloud.discoveryengine_v1alpha.services.sample_query_service",
    "google.cloud.discoveryengine_v1alpha.services.site_search_engine_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.session_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.serving_config_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.document_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.user_event_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.project_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.completion_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.data_store_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.grounded_generation_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.estimate_billing_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.search_tuning_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.chunk_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.sample_query_set_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.control_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.recommendation_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.rank_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.engine_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.conversational_search_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.schema_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.evaluation_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.acl_config_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.search_service.transports",
    "google.cloud.discoveryengine_v1alpha.services.sample_query_service.transports",
    "google.cloud.discoveryengine_v1beta.services",
    "google.cloud.discoveryengine_v1beta.types",
    "google.cloud.discoveryengine_v1beta.services.site_search_engine_service",
    "google.cloud.discoveryengine_v1beta.services.session_service",
    "google.cloud.discoveryengine_v1beta.services.serving_config_service",
    "google.cloud.discoveryengine_v1beta.services.document_service",
    "google.cloud.discoveryengine_v1beta.services.user_event_service",
    "google.cloud.discoveryengine_v1beta.services.project_service",
    "google.cloud.discoveryengine_v1beta.services.completion_service",
    "google.cloud.discoveryengine_v1beta.services.data_store_service",
    "google.cloud.discoveryengine_v1beta.services.grounded_generation_service",
    "google.cloud.discoveryengine_v1beta.services.search_tuning_service",
    "google.cloud.discoveryengine_v1beta.services.sample_query_set_service",
    "google.cloud.discoveryengine_v1beta.services.control_service",
    "google.cloud.discoveryengine_v1beta.services.recommendation_service",
    "google.cloud.discoveryengine_v1beta.services.rank_service",
    "google.cloud.discoveryengine_v1beta.services.engine_service",
    "google.cloud.discoveryengine_v1beta.services.conversational_search_service",
    "google.cloud.discoveryengine_v1beta.services.schema_service",
    "google.cloud.discoveryengine_v1beta.services.evaluation_service",
    "google.cloud.discoveryengine_v1beta.services.search_service",
    "google.cloud.discoveryengine_v1beta.services.sample_query_service",
    "google.cloud.discoveryengine_v1beta.services.site_search_engine_service.transports",
    "google.cloud.discoveryengine_v1beta.services.session_service.transports",
    "google.cloud.discoveryengine_v1beta.services.serving_config_service.transports",
    "google.cloud.discoveryengine_v1beta.services.document_service.transports",
    "google.cloud.discoveryengine_v1beta.services.user_event_service.transports",
    "google.cloud.discoveryengine_v1beta.services.project_service.transports",
    "google.cloud.discoveryengine_v1beta.services.completion_service.transports",
    "google.cloud.discoveryengine_v1beta.services.data_store_service.transports",
    "google.cloud.discoveryengine_v1beta.services.grounded_generation_service.transports",
    "google.cloud.discoveryengine_v1beta.services.search_tuning_service.transports",
    "google.cloud.discoveryengine_v1beta.services.sample_query_set_service.transports",
    "google.cloud.discoveryengine_v1beta.services.control_service.transports",
    "google.cloud.discoveryengine_v1beta.services.recommendation_service.transports",
    "google.cloud.discoveryengine_v1beta.services.rank_service.transports",
    "google.cloud.discoveryengine_v1beta.services.engine_service.transports",
    "google.cloud.discoveryengine_v1beta.services.conversational_search_service.transports",
    "google.cloud.discoveryengine_v1beta.services.schema_service.transports",
    "google.cloud.discoveryengine_v1beta.services.evaluation_service.transports",
    "google.cloud.discoveryengine_v1beta.services.search_service.transports",
    "google.cloud.discoveryengine_v1beta.services.sample_query_service.transports",
    "google.cloud.discoveryengine_v1.services",
    "google.cloud.discoveryengine_v1.types",
    "google.cloud.discoveryengine_v1.services.site_search_engine_service",
    "google.cloud.discoveryengine_v1.services.cmek_config_service",
    "google.cloud.discoveryengine_v1.services.session_service",
    "google.cloud.discoveryengine_v1.services.serving_config_service",
    "google.cloud.discoveryengine_v1.services.document_service",
    "google.cloud.discoveryengine_v1.services.user_event_service",
    "google.cloud.discoveryengine_v1.services.project_service",
    "google.cloud.discoveryengine_v1.services.completion_service",
    "google.cloud.discoveryengine_v1.services.data_store_service",
    "google.cloud.discoveryengine_v1.services.grounded_generation_service",
    "google.cloud.discoveryengine_v1.services.search_tuning_service",
    "google.cloud.discoveryengine_v1.services.user_license_service",
    "google.cloud.discoveryengine_v1.services.assistant_service",
    "google.cloud.discoveryengine_v1.services.control_service",
    "google.cloud.discoveryengine_v1.services.identity_mapping_store_service",
    "google.cloud.discoveryengine_v1.services.recommendation_service",
    "google.cloud.discoveryengine_v1.services.rank_service",
    "google.cloud.discoveryengine_v1.services.engine_service",
    "google.cloud.discoveryengine_v1.services.conversational_search_service",
    "google.cloud.discoveryengine_v1.services.schema_service",
    "google.cloud.discoveryengine_v1.services.search_service",
    "google.cloud.discoveryengine_v1.services.site_search_engine_service.transports",
    "google.cloud.discoveryengine_v1.services.cmek_config_service.transports",
    "google.cloud.discoveryengine_v1.services.session_service.transports",
    "google.cloud.discoveryengine_v1.services.serving_config_service.transports",
    "google.cloud.discoveryengine_v1.services.document_service.transports",
    "google.cloud.discoveryengine_v1.services.user_event_service.transports",
    "google.cloud.discoveryengine_v1.services.project_service.transports",
    "google.cloud.discoveryengine_v1.services.completion_service.transports",
    "google.cloud.discoveryengine_v1.services.data_store_service.transports",
    "google.cloud.discoveryengine_v1.services.grounded_generation_service.transports",
    "google.cloud.discoveryengine_v1.services.search_tuning_service.transports",
    "google.cloud.discoveryengine_v1.services.user_license_service.transports",
    "google.cloud.discoveryengine_v1.services.assistant_service.transports",
    "google.cloud.discoveryengine_v1.services.control_service.transports",
    "google.cloud.discoveryengine_v1.services.identity_mapping_store_service.transports",
    "google.cloud.discoveryengine_v1.services.recommendation_service.transports",
    "google.cloud.discoveryengine_v1.services.rank_service.transports",
    "google.cloud.discoveryengine_v1.services.engine_service.transports",
    "google.cloud.discoveryengine_v1.services.conversational_search_service.transports",
    "google.cloud.discoveryengine_v1.services.schema_service.transports",
    "google.cloud.discoveryengine_v1.services.search_service.transports",
]
include-package-data = true
