[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "msrest"
version = "0.7.1"
description = "AutoRest swagger generator Python client runtime."
readme = "README.rst"
requires-python = ">=3.6"
license = {text = "MIT License"}
authors = [
    {name = "Microsoft Corporation"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development",
]
dependencies = [
    "requests~=2.16",
    "requests_oauthlib>=0.5.0",
    "isodate>=0.6.0",
    "certifi>=2017.4.17",
    "azure-core>=1.24.0",
]

[project.urls]
"Homepage" = "https://github.com/Azure/msrest-for-python"

[project.optional-dependencies]
"async" = [
    "aiohttp>=3.0; python_version >= '3.5'",
    "aiodns; python_version >= '3.5'",
]

[tool.setuptools]
packages = [
    "msrest",
    "msrest.pipeline",
    "msrest.universal_http",
    "msrest.polling",
]
include-package-data = true

[tool.setuptools.package-data]
"pytyped" = [
    "py.typed",
]
