[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "fqdn"
version = "1.5.1"
description = "Validates fully-qualified domain names against RFC 1123, so that they are acceptable to modern bowsers"
keywords = [ "fqdn", "domain", "hostname", "RFC3686", "dns",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Web Environment", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)", "Operating System :: OS Independent", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Internet :: Name Service (DNS)", "Topic :: Internet", "Topic :: System :: Systems Administration", "Topic :: Utilities",]
readme = "README.rst"
requires-python = ">=2.7, !=3.0, !=3.1, !=3.2, !=3.3, !=3.4, <4"
dependencies = [ "cached-property>=1.3.0;python_version<'3.8'",]
[[project.authors]]
name = "ypcrts"
email = "ypcrts@users.noreply.github.com"

[project.license]
text = "MPL 2.0"

[project.urls]
Homepage = "https://github.com/ypcrts/fqdn"

[tool.setuptools]
packages = [ "fqdn",]
zip-safe = true
include-package-data = false
