[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "azure-devops"
version = "7.1.0b4"
description = "Python wrapper around the Azure DevOps 7.x APIs"
keywords = [
    "Microsoft",
    "VSTS",
    "Team Services",
    "SDK",
    "AzureTfs",
    "AzureDevOps",
    "DevOps",
]
license = {text = "MIT"}
authors = [
    {name = "Microsoft Corporation"},
]
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "msrest>=0.7.1,<0.8.0",
]

[project.readme]
text = "Azure DevOps Python clients"
content-type = "text/plain"

[project.urls]
Homepage = "https://github.com/microsoft/azure-devops-python-api"

[tool.setuptools]
include-package-data = true
packages = [
    "azure",
    "azure.devops",
    "azure.devops.issue_tests",
    "azure.devops.released",
    "azure.devops.released.accounts",
    "azure.devops.released.build",
    "azure.devops.released.cix",
    "azure.devops.released.core",
    "azure.devops.released.elastic",
    "azure.devops.released.feed",
    "azure.devops.released.git",
    "azure.devops.released.graph",
    "azure.devops.released.identity",
    "azure.devops.released.member_entitlement_management",
    "azure.devops.released.notification",
    "azure.devops.released.npm",
    "azure.devops.released.nuget",
    "azure.devops.released.operations",
    "azure.devops.released.pipelines",
    "azure.devops.released.policy",
    "azure.devops.released.profile",
    "azure.devops.released.project_analysis",
    "azure.devops.released.release",
    "azure.devops.released.search",
    "azure.devops.released.security",
    "azure.devops.released.service_endpoint",
    "azure.devops.released.service_hooks",
    "azure.devops.released.symbol",
    "azure.devops.released.task",
    "azure.devops.released.task_agent",
    "azure.devops.released.test",
    "azure.devops.released.test_plan",
    "azure.devops.released.test_results",
    "azure.devops.released.tfvc",
    "azure.devops.released.token_admin",
    "azure.devops.released.wiki",
    "azure.devops.released.work",
    "azure.devops.released.work_item_tracking",
    "azure.devops.released.work_item_tracking_process",
    "azure.devops.released.work_item_tracking_process_template",
    "azure.devops.v7_0",
    "azure.devops.v7_0.accounts",
    "azure.devops.v7_0.audit",
    "azure.devops.v7_0.build",
    "azure.devops.v7_0.cix",
    "azure.devops.v7_0.client_trace",
    "azure.devops.v7_0.contributions",
    "azure.devops.v7_0.core",
    "azure.devops.v7_0.customer_intelligence",
    "azure.devops.v7_0.dashboard",
    "azure.devops.v7_0.elastic",
    "azure.devops.v7_0.extension_management",
    "azure.devops.v7_0.feature_availability",
    "azure.devops.v7_0.feature_management",
    "azure.devops.v7_0.feed",
    "azure.devops.v7_0.file_container",
    "azure.devops.v7_0.gallery",
    "azure.devops.v7_0.git",
    "azure.devops.v7_0.graph",
    "azure.devops.v7_0.identity",
    "azure.devops.v7_0.location",
    "azure.devops.v7_0.maven",
    "azure.devops.v7_0.member_entitlement_management",
    "azure.devops.v7_0.notification",
    "azure.devops.v7_0.npm",
    "azure.devops.v7_0.nuget",
    "azure.devops.v7_0.operations",
    "azure.devops.v7_0.pipeline_permissions",
    "azure.devops.v7_0.pipelines",
    "azure.devops.v7_0.pipelines_checks",
    "azure.devops.v7_0.policy",
    "azure.devops.v7_0.profile",
    "azure.devops.v7_0.profile_regions",
    "azure.devops.v7_0.project_analysis",
    "azure.devops.v7_0.provenance",
    "azure.devops.v7_0.py_pi_api",
    "azure.devops.v7_0.release",
    "azure.devops.v7_0.sbom",
    "azure.devops.v7_0.search",
    "azure.devops.v7_0.security",
    "azure.devops.v7_0.service_endpoint",
    "azure.devops.v7_0.service_hooks",
    "azure.devops.v7_0.settings",
    "azure.devops.v7_0.symbol",
    "azure.devops.v7_0.task",
    "azure.devops.v7_0.task_agent",
    "azure.devops.v7_0.test",
    "azure.devops.v7_0.test_plan",
    "azure.devops.v7_0.test_results",
    "azure.devops.v7_0.tfvc",
    "azure.devops.v7_0.token_admin",
    "azure.devops.v7_0.upack_api",
    "azure.devops.v7_0.upack_packaging",
    "azure.devops.v7_0.wiki",
    "azure.devops.v7_0.work",
    "azure.devops.v7_0.work_item_tracking",
    "azure.devops.v7_0.work_item_tracking_process",
    "azure.devops.v7_0.work_item_tracking_process_template",
    "azure.devops.v7_1",
    "azure.devops.v7_1.accounts",
    "azure.devops.v7_1.audit",
    "azure.devops.v7_1.build",
    "azure.devops.v7_1.cix",
    "azure.devops.v7_1.client_trace",
    "azure.devops.v7_1.contributions",
    "azure.devops.v7_1.core",
    "azure.devops.v7_1.customer_intelligence",
    "azure.devops.v7_1.dashboard",
    "azure.devops.v7_1.elastic",
    "azure.devops.v7_1.extension_management",
    "azure.devops.v7_1.feature_availability",
    "azure.devops.v7_1.feature_management",
    "azure.devops.v7_1.feed",
    "azure.devops.v7_1.file_container",
    "azure.devops.v7_1.gallery",
    "azure.devops.v7_1.git",
    "azure.devops.v7_1.graph",
    "azure.devops.v7_1.identity",
    "azure.devops.v7_1.location",
    "azure.devops.v7_1.maven",
    "azure.devops.v7_1.member_entitlement_management",
    "azure.devops.v7_1.notification",
    "azure.devops.v7_1.npm",
    "azure.devops.v7_1.nuget",
    "azure.devops.v7_1.operations",
    "azure.devops.v7_1.pipeline_permissions",
    "azure.devops.v7_1.pipelines",
    "azure.devops.v7_1.pipelines_checks",
    "azure.devops.v7_1.policy",
    "azure.devops.v7_1.profile",
    "azure.devops.v7_1.profile_regions",
    "azure.devops.v7_1.project_analysis",
    "azure.devops.v7_1.provenance",
    "azure.devops.v7_1.py_pi_api",
    "azure.devops.v7_1.release",
    "azure.devops.v7_1.sbom",
    "azure.devops.v7_1.search",
    "azure.devops.v7_1.security",
    "azure.devops.v7_1.service_endpoint",
    "azure.devops.v7_1.service_hooks",
    "azure.devops.v7_1.settings",
    "azure.devops.v7_1.symbol",
    "azure.devops.v7_1.task",
    "azure.devops.v7_1.task_agent",
    "azure.devops.v7_1.test",
    "azure.devops.v7_1.test_plan",
    "azure.devops.v7_1.test_results",
    "azure.devops.v7_1.tfvc",
    "azure.devops.v7_1.token_admin",
    "azure.devops.v7_1.upack_api",
    "azure.devops.v7_1.upack_packaging",
    "azure.devops.v7_1.wiki",
    "azure.devops.v7_1.work",
    "azure.devops.v7_1.work_item_tracking",
    "azure.devops.v7_1.work_item_tracking_process",
    "azure.devops.v7_1.work_item_tracking_process_template",
]
