[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "jsonlines"
version = "4.0.0"
description = "Library with helpers for the jsonlines file format"
readme = "README.rst"
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "License :: OSI Approved :: BSD License", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only", "Topic :: Internet :: Log Analysis", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: System :: Logging", "Topic :: Utilities",]
requires-python = ">=3.8"
dependencies = [ "attrs>=19.2.0",]

[[project.authors]]
name = "wouter bolsterlee"
email = "wouter@bolsterl.ee"

[project.license]
text = "BSD"

[project.urls]
Homepage = "https://github.com/wbolster/jsonlines"

[tool.setuptools]
packages = [ "jsonlines",]
license-files = [ "LICENSE.rst",]
include-package-data = false

[tool.setuptools.package-data]
jsonlines = [ "py.typed",]
