[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "influxdb"
version = "5.3.2"
description = "InfluxDB client"
readme = "README.rst"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Topic :: Software Development :: Libraries", "Topic :: Software Development :: Libraries :: Python Modules",]
dependencies = [ "python-dateutil>=2.6.0", "pytz", "requests>=2.17.0", "six>=1.10.0", "msgpack",]

[project.license]
text = "MIT License"

[project.urls]
Homepage = "https://github.com/influxdb/influxdb-python"

[project.optional-dependencies]
test = [ "nose", "nose-cov", "mock", "requests-mock",]
testing = [ "nose", "nose-cov", "mock", "requests-mock",]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
