[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "Js2Py"
version = "0.74"
description = "JavaScript to Python Translator & JavaScript interpreter written in 100% pure Python."
readme = {text = "Translates JavaScript to Python code. Js2Py is able to translate and execute virtually any JavaScript code.\n\nJs2Py is written in pure python and does not have any dependencies. Basically an implementation of JavaScript core in pure python.\n\n\n    import js2py\n\n    f = js2py.eval_js( \"function $(name) {return name.length}\" )\n\n    f(\"Hello world\")\n\n    # returns 11\n\nNow also supports ECMA 6 through js2py.eval_js6(js6_code)!\n\nMore examples at: https://github.com/PiotrDabkowski/Js2Py\n", content-type = "text/plain"}
license = {text = "MIT"}
authors = [
    {name = "Piotr Dabkowski", email = "piodrus@gmail.com"},
]
dependencies = [
    "tzlocal>=1.2",
    "six>=1.10",
    "pyjsparser>=2.5.1",
]

[project.urls]
"Homepage" = "https://github.com/PiotrDabkowski/Js2Py"

[tool.setuptools]
packages = [
    "js2py",
    "js2py.utils",
    "js2py.prototypes",
    "js2py.translators",
    "js2py.constructors",
    "js2py.host",
    "js2py.es6",
    "js2py.internals",
    "js2py.internals.prototypes",
    "js2py.internals.constructors",
    "js2py.py_node_modules",
]
include-package-data = false
