[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "namex"
version = "0.1.0"
description = "A simple utility to separate the implementation of your Python package and its public API surface."

[[project.authors]]
name = "Francois Chollet"
email = "francois.chollet@gmail.com"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
