[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "haversine"
version = "2.9.0"
description = "Calculate the distance between 2 points on Earth."
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Topic :: Scientific/Engineering :: Mathematics", "Topic :: Scientific/Engineering :: GIS",]
requires-python = ">=3.5"

[[project.authors]]
name = "Balthazar Rouberol"

[[project.maintainers]]
name = "Julien Deniau"
email = "julien.deniau@mapado.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/mapado/haversine"

[tool.setuptools]
packages = [ "haversine",]
include-package-data = true
