[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "boxsdk"
version = "10.11.0"
description = "Official Box Python SDK"
keywords = [ "box", "sdk", "api", "rest", "boxsdk", "box-sdk-gen",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Operating System :: OS Independent", "Operating System :: POSIX", "Operating System :: Microsoft :: Windows", "Operating System :: MacOS :: MacOS X", "Topic :: Software Development :: Libraries :: Python Modules",]
dependencies = [ "requests", "requests-toolbelt",]

[[project.authors]]
name = "Box"
email = "oss@box.com"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/box/box-python-sdk.git"

[project.optional-dependencies]
test = [ "pytest", "pytest-timeout", "pytest-cov", "pytest-rerunfailures", "pytest-xdist", "pyjwt>=1.7.0", "cryptography>=3",]
dev = [ "tox",]
jwt = [ "pyjwt>=1.7.0", "cryptography>=3",]
testing = [ "pytest", "pytest-timeout", "pytest-cov", "pytest-rerunfailures", "pytest-xdist",]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "docs",]
namespaces = false
