[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "google_api"
version = "0.1.12"
description = "Google API Client"
keywords = [ "google", "api",]
classifiers = [ "Development Status :: 3 - Alpha", "Topic :: Utilities", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.0", "Programming Language :: Python :: 3.1", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6",]
dependencies = [ "appier",]

[[project.authors]]
name = "Hive Solutions Lda."
email = "development@hive.pt"

[project.license]
text = "Apache License, Version 2.0"

[project.urls]
Homepage = "http://google-api.hive.pt"

[tool.setuptools]
packages = [ "google",]
zip-safe = false
include-package-data = false

[tool.setuptools.package-dir]
"" = "src"
