[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "langdetect"
version = "1.0.9"
description = "Language detection library ported from Google's language-detection."
keywords = [ "language", "detection", "library",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8",]
dependencies = [ "six",]

[[project.authors]]
name = "Michal Mimino Danilak"
email = "michal.danilak@gmail.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/Mimino666/langdetect"

[tool.setuptools]
packages = [ "langdetect", "langdetect.utils", "langdetect.tests",]
include-package-data = true
