[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "ecdsa"
version = "0.19.2"
description = "ECDSA cryptographic signature library (pure python)"
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13",]
requires-python = ">=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
dependencies = [ "six>=1.9.0",]

[[project.authors]]
name = "Brian Warner"
email = "warner@lothar.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "http://github.com/tlsfuzzer/python-ecdsa"

[project.optional-dependencies]
gmpy2 = [ "gmpy2",]
gmpy = [ "gmpy",]

[tool.setuptools]
packages = [ "ecdsa",]
include-package-data = false

[tool.setuptools.package-dir]
"" = "src"
