[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "fastjsonschema"
version = "2.21.2"
description = "Fastest Python implementation of JSON schema"
readme = "README.rst"
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: Implementation :: CPython", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Topic :: Software Development :: Libraries :: Python Modules",]

[[project.authors]]
name = "Michal Horejsek"
email = "fastjsonschema@horejsek.com"

[project.license]
text = "BSD"

[project.urls]
Homepage = "https://github.com/horejsek/python-fastjsonschema"

[project.optional-dependencies]
devel = [ "colorama", "jsonschema", "json-spec", "pylint", "pytest", "pytest-benchmark", "pytest-cache", "validictory",]

[tool.setuptools]
packages = [ "fastjsonschema",]
include-package-data = false
