[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "websocket-client"
version = "1.9.0"
description = "WebSocket client for Python with low level API options"
keywords = [ "websockets", "client",]
classifiers = [ "Development Status :: 4 - Beta", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Operating System :: MacOS :: MacOS X", "Operating System :: POSIX", "Operating System :: Microsoft :: Windows", "Topic :: Internet", "Topic :: Software Development :: Libraries :: Python Modules", "Intended Audience :: Developers",]
requires-python = ">=3.9"
dependencies = []
[[project.authors]]
name = "liris"
email = "liris.pp@gmail.com"

[[project.maintainers]]
name = "engn33r"
email = "websocket.client@proton.me"

[project.license]
text = "Apache-2.0"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/websocket-client/websocket-client.git"
Download = "https://github.com/websocket-client/websocket-client/releases"
Documentation = "https://websocket-client.readthedocs.io/"
Source = "https://github.com/websocket-client/websocket-client/"

[project.optional-dependencies]
test = [ "pytest", "websockets",]
optional = [ "python-socks", "wsaccel",]
docs = [ "Sphinx >= 6.0", "sphinx_rtd_theme >= 1.1.0", "myst-parser >= 2.0.0",]
testing = []

[project.scripts]
wsdump = "websocket._wsdump:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"websocket.tests" = [ "data/*.txt",]

[tool.setuptools.packages.find]
namespaces = false
