[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "google-resumable-media"
version = "2.10.0"
description = "Utilities for Google Media Downloads and Resumable Uploads"
readme = "README.rst"
license = {text = "Apache 2.0"}
authors = [
  {name = "Google Cloud Platform", email = "googleapis-publisher@google.com"},
]
requires-python = ">= 3.10"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet",
]
dependencies = ["google-crc32c >= 1.0.0, < 2.0.0"]

[project.optional-dependencies]
requests = ["requests >= 2.18.0, < 3.0.0"]
aiohttp = ["aiohttp >= 3.6.2, < 4.0.0", "google-auth >= 1.22.0, < 2.0.0"]

[project.urls]
Homepage = "https://github.com/googleapis/google-cloud-python/tree/main/packages/google-resumable-media"

[tool.setuptools]
include-package-data = true
platforms = ["Posix; MacOS X; Windows"]
packages = [
  "google",
  "google.resumable_media",
  "google._async_resumable_media",
  "google.resumable_media.requests",
  "google._async_resumable_media.requests",
]
