[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "plotext"
version = "5.3.2"
description = "plotext plots directly on terminal"
classifiers = []
requires-python = ">=3.5"
dependencies = []
[[project.authors]]
name = "Savino Piccolomo"
email = "piccolomo@gmail.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/piccolomo/plotext"

[project.optional-dependencies]
image = [ "pillow>=8.4",]
video = [ "pillow>=8.4", "pafy>=0.5.5", "opencv-python>=4.5.5", "ffpyplayer>=4.3.5", "youtube-dl==2020.12.2",]
completion = [ "shtab",]

[project.scripts]
plotext = "plotext.plotext_cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
