[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "aniso8601"
version = "10.0.1"
description = "A library for parsing ISO 8601 strings."
keywords = [ "iso8601", "parser",]
classifiers = [ "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Topic :: Software Development :: Libraries :: Python Modules",]
[[project.authors]]
name = "Brandon Nielsen"
email = "nielsenb@jetfuse.net"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://codeberg.org/nielsenb-jf/aniso8601"
Changelog = "https://codeberg.org/nielsenb-jf/aniso8601/src/branch/main/CHANGELOG.rst"
Documentation = "https://aniso8601.readthedocs.io/"
Source = "https://codeberg.org/nielsenb-jf/aniso8601"
Tracker = "https://codeberg.org/nielsenb-jf/aniso8601/issues"

[project.optional-dependencies]
dev = [ "black", "coverage", "isort", "pre-commit", "pyenchant", "pylint",]
testing = []

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
