[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "jsonpointer"
version = "3.1.1"
description = "Identify specific nodes in a JSON document (RFC 6901)"
classifiers = [ "Development Status :: 5 - Production/Stable", "Environment :: Console", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Software Development :: Libraries", "Topic :: Utilities",]
requires-python = ">=3.10"

[[project.authors]]
name = "Stefan Kögl"
email = "stefan@skoegl.net"

[project.license]
text = "Modified BSD License"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/stefankoegl/python-json-pointer"

[tool.setuptools]
py-modules = [ "jsonpointer",]
script-files = [ "bin/jsonpointer",]
include-package-data = false
