[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "google-cloud-compute"
version = "1.48.0"
description = "Google Cloud Compute API client library"
readme = "README.rst"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [
    {name = "Google LLC", email = "googleapis-packages@google.com"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Internet",
]
dependencies = [
    "google-api-core[grpc] >= 2.17.1, <3.0.0",
    "google-auth >= 2.14.1, <3.0.0,!=2.24.0,!=2.25.0",
    "grpcio >= 1.59.0, < 2.0.0",
    "grpcio >= 1.75.1, < 2.0.0; python_version >= '3.14'",
    "proto-plus >= 1.22.3, <2.0.0",
    "proto-plus >= 1.25.0, <2.0.0; python_version >= '3.13'",
    "protobuf >= 4.25.8, < 8.0.0",
]

[project.urls]
"Homepage" = "https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-compute"

[tool.setuptools]
packages = [
    "google",
    "google.cloud",
    "google.cloud.compute_v1",
    "google.cloud.compute",
    "google.cloud.compute_v1.services",
    "google.cloud.compute_v1.types",
    "google.cloud.compute_v1.services.disks",
    "google.cloud.compute_v1.services.regions",
    "google.cloud.compute_v1.services.region_snapshot_settings",
    "google.cloud.compute_v1.services.disk_types",
    "google.cloud.compute_v1.services.region_instance_templates",
    "google.cloud.compute_v1.services.region_instance_group_manager_resize_requests",
    "google.cloud.compute_v1.services.global_network_endpoint_groups",
    "google.cloud.compute_v1.services.region_network_endpoint_groups",
    "google.cloud.compute_v1.services.service_attachments",
    "google.cloud.compute_v1.services.region_instances",
    "google.cloud.compute_v1.services.reservation_slots",
    "google.cloud.compute_v1.services.future_reservations",
    "google.cloud.compute_v1.services.preview_features",
    "google.cloud.compute_v1.services.network_attachments",
    "google.cloud.compute_v1.services.image_family_views",
    "google.cloud.compute_v1.services.target_instances",
    "google.cloud.compute_v1.services.licenses",
    "google.cloud.compute_v1.services.security_policies",
    "google.cloud.compute_v1.services.external_vpn_gateways",
    "google.cloud.compute_v1.services.region_health_checks",
    "google.cloud.compute_v1.services.node_groups",
    "google.cloud.compute_v1.services.instances",
    "google.cloud.compute_v1.services.global_vm_extension_policies",
    "google.cloud.compute_v1.services.instance_group_manager_resize_requests",
    "google.cloud.compute_v1.services.vpn_tunnels",
    "google.cloud.compute_v1.services.region_target_http_proxies",
    "google.cloud.compute_v1.services.region_health_aggregation_policies",
    "google.cloud.compute_v1.services.network_edge_security_services",
    "google.cloud.compute_v1.services.region_instant_snapshots",
    "google.cloud.compute_v1.services.cross_site_networks",
    "google.cloud.compute_v1.services.resource_policies",
    "google.cloud.compute_v1.services.snapshots",
    "google.cloud.compute_v1.services.region_url_maps",
    "google.cloud.compute_v1.services.advice",
    "google.cloud.compute_v1.services.region_instance_groups",
    "google.cloud.compute_v1.services.region_instant_snapshot_groups",
    "google.cloud.compute_v1.services.region_notification_endpoints",
    "google.cloud.compute_v1.services.ssl_policies",
    "google.cloud.compute_v1.services.network_firewall_policies",
    "google.cloud.compute_v1.services.region_composite_health_checks",
    "google.cloud.compute_v1.services.license_codes",
    "google.cloud.compute_v1.services.target_http_proxies",
    "google.cloud.compute_v1.services.region_ssl_certificates",
    "google.cloud.compute_v1.services.interconnect_groups",
    "google.cloud.compute_v1.services.accelerator_types",
    "google.cloud.compute_v1.services.region_backend_buckets",
    "google.cloud.compute_v1.services.addresses",
    "google.cloud.compute_v1.services.storage_pools",
    "google.cloud.compute_v1.services.region_security_policies",
    "google.cloud.compute_v1.services.url_maps",
    "google.cloud.compute_v1.services.wire_groups",
    "google.cloud.compute_v1.services.images",
    "google.cloud.compute_v1.services.target_ssl_proxies",
    "google.cloud.compute_v1.services.backend_services",
    "google.cloud.compute_v1.services.interconnect_remote_locations",
    "google.cloud.compute_v1.services.region_health_check_services",
    "google.cloud.compute_v1.services.target_tcp_proxies",
    "google.cloud.compute_v1.services.instant_snapshots",
    "google.cloud.compute_v1.services.target_pools",
    "google.cloud.compute_v1.services.global_addresses",
    "google.cloud.compute_v1.services.region_operations",
    "google.cloud.compute_v1.services.backend_buckets",
    "google.cloud.compute_v1.services.node_templates",
    "google.cloud.compute_v1.services.snapshot_settings_service",
    "google.cloud.compute_v1.services.instant_snapshot_groups",
    "google.cloud.compute_v1.services.subnetworks",
    "google.cloud.compute_v1.services.region_network_firewall_policies",
    "google.cloud.compute_v1.services.target_vpn_gateways",
    "google.cloud.compute_v1.services.machine_images",
    "google.cloud.compute_v1.services.target_grpc_proxies",
    "google.cloud.compute_v1.services.region_commitments",
    "google.cloud.compute_v1.services.public_advertised_prefixes",
    "google.cloud.compute_v1.services.zone_vm_extension_policies",
    "google.cloud.compute_v1.services.global_organization_operations",
    "google.cloud.compute_v1.services.rollouts",
    "google.cloud.compute_v1.services.interconnects",
    "google.cloud.compute_v1.services.zones",
    "google.cloud.compute_v1.services.network_profiles",
    "google.cloud.compute_v1.services.instance_groups",
    "google.cloud.compute_v1.services.global_operations",
    "google.cloud.compute_v1.services.routes",
    "google.cloud.compute_v1.services.network_endpoint_groups",
    "google.cloud.compute_v1.services.region_target_https_proxies",
    "google.cloud.compute_v1.services.interconnect_attachment_groups",
    "google.cloud.compute_v1.services.interconnect_locations",
    "google.cloud.compute_v1.services.region_autoscalers",
    "google.cloud.compute_v1.services.instance_settings_service",
    "google.cloud.compute_v1.services.firewall_policies",
    "google.cloud.compute_v1.services.global_forwarding_rules",
    "google.cloud.compute_v1.services.networks",
    "google.cloud.compute_v1.services.target_https_proxies",
    "google.cloud.compute_v1.services.global_public_delegated_prefixes",
    "google.cloud.compute_v1.services.organization_security_policies",
    "google.cloud.compute_v1.services.region_zones",
    "google.cloud.compute_v1.services.zone_operations",
    "google.cloud.compute_v1.services.packet_mirrorings",
    "google.cloud.compute_v1.services.health_checks",
    "google.cloud.compute_v1.services.reservation_sub_blocks",
    "google.cloud.compute_v1.services.routers",
    "google.cloud.compute_v1.services.reservation_blocks",
    "google.cloud.compute_v1.services.interconnect_attachments",
    "google.cloud.compute_v1.services.region_snapshots",
    "google.cloud.compute_v1.services.region_instance_group_managers",
    "google.cloud.compute_v1.services.instance_templates",
    "google.cloud.compute_v1.services.reservations",
    "google.cloud.compute_v1.services.region_health_sources",
    "google.cloud.compute_v1.services.vpn_gateways",
    "google.cloud.compute_v1.services.region_target_tcp_proxies",
    "google.cloud.compute_v1.services.region_backend_services",
    "google.cloud.compute_v1.services.node_types",
    "google.cloud.compute_v1.services.machine_types",
    "google.cloud.compute_v1.services.projects",
    "google.cloud.compute_v1.services.forwarding_rules",
    "google.cloud.compute_v1.services.instance_group_managers",
    "google.cloud.compute_v1.services.ssl_certificates",
    "google.cloud.compute_v1.services.region_ssl_policies",
    "google.cloud.compute_v1.services.region_disks",
    "google.cloud.compute_v1.services.storage_pool_types",
    "google.cloud.compute_v1.services.region_disk_types",
    "google.cloud.compute_v1.services.rollout_plans",
    "google.cloud.compute_v1.services.public_delegated_prefixes",
    "google.cloud.compute_v1.services.autoscalers",
    "google.cloud.compute_v1.services.firewalls",
    "google.cloud.compute_v1.services.disks.transports",
    "google.cloud.compute_v1.services.regions.transports",
    "google.cloud.compute_v1.services.region_snapshot_settings.transports",
    "google.cloud.compute_v1.services.disk_types.transports",
    "google.cloud.compute_v1.services.region_instance_templates.transports",
    "google.cloud.compute_v1.services.region_instance_group_manager_resize_requests.transports",
    "google.cloud.compute_v1.services.global_network_endpoint_groups.transports",
    "google.cloud.compute_v1.services.region_network_endpoint_groups.transports",
    "google.cloud.compute_v1.services.service_attachments.transports",
    "google.cloud.compute_v1.services.region_instances.transports",
    "google.cloud.compute_v1.services.reservation_slots.transports",
    "google.cloud.compute_v1.services.future_reservations.transports",
    "google.cloud.compute_v1.services.preview_features.transports",
    "google.cloud.compute_v1.services.network_attachments.transports",
    "google.cloud.compute_v1.services.image_family_views.transports",
    "google.cloud.compute_v1.services.target_instances.transports",
    "google.cloud.compute_v1.services.licenses.transports",
    "google.cloud.compute_v1.services.security_policies.transports",
    "google.cloud.compute_v1.services.external_vpn_gateways.transports",
    "google.cloud.compute_v1.services.region_health_checks.transports",
    "google.cloud.compute_v1.services.node_groups.transports",
    "google.cloud.compute_v1.services.instances.transports",
    "google.cloud.compute_v1.services.global_vm_extension_policies.transports",
    "google.cloud.compute_v1.services.instance_group_manager_resize_requests.transports",
    "google.cloud.compute_v1.services.vpn_tunnels.transports",
    "google.cloud.compute_v1.services.region_target_http_proxies.transports",
    "google.cloud.compute_v1.services.region_health_aggregation_policies.transports",
    "google.cloud.compute_v1.services.network_edge_security_services.transports",
    "google.cloud.compute_v1.services.region_instant_snapshots.transports",
    "google.cloud.compute_v1.services.cross_site_networks.transports",
    "google.cloud.compute_v1.services.resource_policies.transports",
    "google.cloud.compute_v1.services.snapshots.transports",
    "google.cloud.compute_v1.services.region_url_maps.transports",
    "google.cloud.compute_v1.services.advice.transports",
    "google.cloud.compute_v1.services.region_instance_groups.transports",
    "google.cloud.compute_v1.services.region_instant_snapshot_groups.transports",
    "google.cloud.compute_v1.services.region_notification_endpoints.transports",
    "google.cloud.compute_v1.services.ssl_policies.transports",
    "google.cloud.compute_v1.services.network_firewall_policies.transports",
    "google.cloud.compute_v1.services.region_composite_health_checks.transports",
    "google.cloud.compute_v1.services.license_codes.transports",
    "google.cloud.compute_v1.services.target_http_proxies.transports",
    "google.cloud.compute_v1.services.region_ssl_certificates.transports",
    "google.cloud.compute_v1.services.interconnect_groups.transports",
    "google.cloud.compute_v1.services.accelerator_types.transports",
    "google.cloud.compute_v1.services.region_backend_buckets.transports",
    "google.cloud.compute_v1.services.addresses.transports",
    "google.cloud.compute_v1.services.storage_pools.transports",
    "google.cloud.compute_v1.services.region_security_policies.transports",
    "google.cloud.compute_v1.services.url_maps.transports",
    "google.cloud.compute_v1.services.wire_groups.transports",
    "google.cloud.compute_v1.services.images.transports",
    "google.cloud.compute_v1.services.target_ssl_proxies.transports",
    "google.cloud.compute_v1.services.backend_services.transports",
    "google.cloud.compute_v1.services.interconnect_remote_locations.transports",
    "google.cloud.compute_v1.services.region_health_check_services.transports",
    "google.cloud.compute_v1.services.target_tcp_proxies.transports",
    "google.cloud.compute_v1.services.instant_snapshots.transports",
    "google.cloud.compute_v1.services.target_pools.transports",
    "google.cloud.compute_v1.services.global_addresses.transports",
    "google.cloud.compute_v1.services.region_operations.transports",
    "google.cloud.compute_v1.services.backend_buckets.transports",
    "google.cloud.compute_v1.services.node_templates.transports",
    "google.cloud.compute_v1.services.snapshot_settings_service.transports",
    "google.cloud.compute_v1.services.instant_snapshot_groups.transports",
    "google.cloud.compute_v1.services.subnetworks.transports",
    "google.cloud.compute_v1.services.region_network_firewall_policies.transports",
    "google.cloud.compute_v1.services.target_vpn_gateways.transports",
    "google.cloud.compute_v1.services.machine_images.transports",
    "google.cloud.compute_v1.services.target_grpc_proxies.transports",
    "google.cloud.compute_v1.services.region_commitments.transports",
    "google.cloud.compute_v1.services.public_advertised_prefixes.transports",
    "google.cloud.compute_v1.services.zone_vm_extension_policies.transports",
    "google.cloud.compute_v1.services.global_organization_operations.transports",
    "google.cloud.compute_v1.services.rollouts.transports",
    "google.cloud.compute_v1.services.interconnects.transports",
    "google.cloud.compute_v1.services.zones.transports",
    "google.cloud.compute_v1.services.network_profiles.transports",
    "google.cloud.compute_v1.services.instance_groups.transports",
    "google.cloud.compute_v1.services.global_operations.transports",
    "google.cloud.compute_v1.services.routes.transports",
    "google.cloud.compute_v1.services.network_endpoint_groups.transports",
    "google.cloud.compute_v1.services.region_target_https_proxies.transports",
    "google.cloud.compute_v1.services.interconnect_attachment_groups.transports",
    "google.cloud.compute_v1.services.interconnect_locations.transports",
    "google.cloud.compute_v1.services.region_autoscalers.transports",
    "google.cloud.compute_v1.services.instance_settings_service.transports",
    "google.cloud.compute_v1.services.firewall_policies.transports",
    "google.cloud.compute_v1.services.global_forwarding_rules.transports",
    "google.cloud.compute_v1.services.networks.transports",
    "google.cloud.compute_v1.services.target_https_proxies.transports",
    "google.cloud.compute_v1.services.global_public_delegated_prefixes.transports",
    "google.cloud.compute_v1.services.organization_security_policies.transports",
    "google.cloud.compute_v1.services.region_zones.transports",
    "google.cloud.compute_v1.services.zone_operations.transports",
    "google.cloud.compute_v1.services.packet_mirrorings.transports",
    "google.cloud.compute_v1.services.health_checks.transports",
    "google.cloud.compute_v1.services.reservation_sub_blocks.transports",
    "google.cloud.compute_v1.services.routers.transports",
    "google.cloud.compute_v1.services.reservation_blocks.transports",
    "google.cloud.compute_v1.services.interconnect_attachments.transports",
    "google.cloud.compute_v1.services.region_snapshots.transports",
    "google.cloud.compute_v1.services.region_instance_group_managers.transports",
    "google.cloud.compute_v1.services.instance_templates.transports",
    "google.cloud.compute_v1.services.reservations.transports",
    "google.cloud.compute_v1.services.region_health_sources.transports",
    "google.cloud.compute_v1.services.vpn_gateways.transports",
    "google.cloud.compute_v1.services.region_target_tcp_proxies.transports",
    "google.cloud.compute_v1.services.region_backend_services.transports",
    "google.cloud.compute_v1.services.node_types.transports",
    "google.cloud.compute_v1.services.machine_types.transports",
    "google.cloud.compute_v1.services.projects.transports",
    "google.cloud.compute_v1.services.forwarding_rules.transports",
    "google.cloud.compute_v1.services.instance_group_managers.transports",
    "google.cloud.compute_v1.services.ssl_certificates.transports",
    "google.cloud.compute_v1.services.region_ssl_policies.transports",
    "google.cloud.compute_v1.services.region_disks.transports",
    "google.cloud.compute_v1.services.storage_pool_types.transports",
    "google.cloud.compute_v1.services.region_disk_types.transports",
    "google.cloud.compute_v1.services.rollout_plans.transports",
    "google.cloud.compute_v1.services.public_delegated_prefixes.transports",
    "google.cloud.compute_v1.services.autoscalers.transports",
    "google.cloud.compute_v1.services.firewalls.transports",
]
platforms = [
    "Posix; MacOS X; Windows",
]
include-package-data = true
