[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "restructuredtext_lint"
version = "2.0.2"
description = "reStructuredText linter"
keywords = [ "restructuredtext", "restructured text", "rest", "rst", "lint",]
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: Public Domain", "Operating System :: OS Independent", "Topic :: Text Processing :: Markup",]
dependencies = [ "docutils>=0.11,<1.0",]

[[project.authors]]
name = "Todd Wolfson"
email = "todd@twolfson.com"

[project.license]
text = "UNLICENSE"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://github.com/twolfson/restructuredtext-lint"
Download = "https://github.com/twolfson/restructuredtext-lint/archive/master.zip"

[project.scripts]
restructuredtext-lint = "restructuredtext_lint.cli:main"
rst-lint = "restructuredtext_lint.cli:main"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
