[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "probableparsing"
version = "0.0.1"
description = "Common methods for propbable parsers"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "Intended Audience :: Science/Research", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Operating System :: MacOS :: MacOS X", "Operating System :: Microsoft :: Windows", "Operating System :: POSIX", "Programming Language :: Python :: 2.7", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Scientific/Engineering", "Topic :: Scientific/Engineering :: Information Analysis",]

[project.license]
text = "The MIT License: http://www.opensource.org/licenses/mit-license.php"

[project.urls]
Homepage = "https://github.com/datamade/probableparsing"

[tool.setuptools]
packages = [ "probableparsing",]
include-package-data = false
