[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
name = "asciitree"
version = "0.3.3"
description = "Draws ASCII trees."
readme = "README.rst"
dependencies = []

[[project.authors]]
name = "Marc Brinkmann"
email = "git@marcbrinkmann.de"

[project.license]
text = "MIT"

[project.urls]
Homepage = "http://github.com/mbr/asciitree"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
exclude = [ "tests",]
namespaces = false
